---
packages:
  - jq
  - rsync
  - tcpdump
  - vim
  - zsh

users_to_manage:
  - name: gino
    groups: "{{ 'wheel' if ansible_facts['os_family'] == 'RedHat' else 'sudo' }}, docker"
    host_access:
      - all
